"""V2 domain contracts.

The package is intentionally isolated from the legacy ``models`` module while
the production session is migrated.  New code should depend on these contracts
through the V2 ports instead of importing Storyboard types.
"""

# These compatibility-only aliases remain importable for existing in-repository
# callers while staying out of the supported ``__all__`` facade.
# ruff: noqa: F401

from .models import (
    CameraInstruction,
    CameraPlan,
    CharacterSheet,
    CharacterSheetEntry,
    ContinuityEntry,
    ContinuityPlan,
    CreativeBrief,
    DirectorPlan,
    EmotionPoint,
    FilmBeatPlan,
    MoviePlan,
    MusicPlan,
    NarrationPlan,
    NarrationSegment,
    ScenePlan,
    ScenePlanEntry,
    Script,
    ScriptScene,
    ShotPlan,
    Story,
    StoryCharacterGoal,
    StoryPlan,
    TimingEntry,
    TimingPlan,
    TransitionInstruction,
    TransitionPlan,
    as_plain_data,
)
from .execution import (
    CompilationOptions,
    CompileDiagnostic,
    CompileError,
    CompileResult,
    ProviderCapabilities,
    ProviderJob,
    RetakeRequest,
    VideoJob,
)
from .provider_contracts import CapabilitySnapshot, ProviderAssignment
from .artifact_contracts import ExpectedArtifact, ReferenceInput, RetryPolicy, TimeoutPolicy
from .execution_plan import (
    ArtifactPolicy,
    DependencyEdge,
    ExecutionPlan,
    ExecutionUnit,
    ReferenceFrameStrategy,
    RuntimePolicy,
)
from .execution_bundle import ExecutionBundle
from .execution_fingerprint import (
    execution_bundle_fingerprint,
    execution_plan_fingerprint,
    execution_unit_fingerprint,
    video_job_fingerprint,
)
from .execution_plan_builder import (
    ExecutionPlanCompileDiagnostic,
    ExecutionPlanCompileError,
    ExecutionPlanCompileResult,
    ExecutionPlanCompiler,
    compile_movie_ir_to_execution_bundle,
)
from .execution_plan_validation import (
    ExecutionValidationDiagnostic,
    ExecutionValidationResult,
    validate_execution_bundle,
    validate_execution_plan,
)
from .execution_state import (
    ExecutionRun,
    ExecutionRunStatus,
    ExecutionState,
    ExecutionUnitState,
    ProviderJob as RuntimeProviderJob,
    RuntimeErrorRecord,
)
from .execution_events import (
    InMemoryExecutionEventStore,
    JsonExecutionEventStore,
    RuntimeEvent,
)
from .runtime_state_store import (
    ExecutionLease,
    InMemoryRuntimeStateStore,
    JsonRuntimeStateStore,
    RetryRecord,
    SubmissionIntent,
)
from .execution_checkpoint import (
    ExecutionCheckpoint,
    InMemoryCheckpointStore,
    JsonCheckpointStore,
)
from .provider_runtime import (
    FakeClock,
    ProviderRequestContext,
    ProviderRuntime,
    ProviderDownloadResult,
    ProviderPollResult,
    ProviderRuntimeError,
    SystemClock,
)
from .provider_capabilities import DurationRange, ProviderCapabilities as RuntimeProviderCapabilities
from .provider_errors import ProviderErrorCategory
from .provider_results import (
    DownloadDestination,
    ProviderCancelResult,
    ProviderJobStatus,
    ProviderSubmitResult,
    ProviderVerificationResult,
    SanitizedOutputLocator,
)
from .fake_provider_runtime import FakeProviderRuntime, FakeProviderScenario
from .http_transport import HttpResponse, HttpTransport
from .mock_http_transport import MockHttpRequest, MockHttpTransport
from .mock_http_provider_runtime import MockHttpProviderRuntime
from .fake_artifact_verifier import ArtifactRecord, ArtifactVerificationResult, FakeArtifactVerifier
from .provider_registry import ProviderNotRegisteredError, ProviderRegistrationError, ProviderRuntimeRegistry
from .execution_scheduler import (
    DependencyResolver,
    RuntimeTransition,
    RuntimeTransitionService,
    TransitionRejectedError,
)
from .execution_runtime import (
    ExecutionRuntime,
    ExecutionRuntimeError,
    RuntimeNotFoundError,
    StaleExecutionRuntimeError,
)
from .compiler import MoviePlanCompiler, VideoJobCompiler, compile_movie_plan_to_video_job
from .film_ir import (
    BeatTimelineEntry,
    CharacterEmotionAnchor,
    CinematicBeat,
    CinematicIR,
    DramaticPurpose,
    EmotionCurvePoint,
    FilmAcceptanceCriterion,
    FilmBeat,
    FilmCharacterAnchor,
    FilmContinuityIntent,
    FilmIR,
    FilmMusicIntent,
    FilmNarrationIntent,
    FilmShot,
    FilmTransitionIntent,
    NarrativeFunction,
    RequiredAudienceUnderstanding,
    RequiredEvidence,
    TensionCurvePoint,
    ViewerState,
    VisualFocus,
)
from .film_ir_builder import (
    FilmIRBuildDiagnostic,
    FilmIRBuildError,
    FilmIRBuildResult,
    FilmIRBuilder,
    CinematicIRBuilder,
    build_cinematic_ir,
    build_film_ir,
)
from .ir_builder import IRBuildDiagnostic, IRBuildError, IRBuildResult, MovieIRBuilder, build_movie_ir
from .ir import (
    AcceptanceCriterion,
    CharacterAnchor,
    ContinuityAnchor,
    MovieIR,
    MusicCue,
    NarrationCue,
    ShotIR,
    SubtitleCue,
    TimelineEntry,
    TransitionCue,
)
from .director import DirectorAgent, DirectorOutputRejected, DirectorOrchestrator
from .openai_director import (
    DirectorGenerationError,
    OpenAIDirectorAgent,
    RuleBasedDirectorAgent,
    movie_plan_from_data,
)
from .validation import ValidationReport, validate_movie_plan, validate_video_job
from .validation import FilmIRValidator, MovieIRValidator, ValidationIssue, ValidationResult
from .passes import (
    CompilerPassPipeline,
    ContinuityDiagnosticsPass,
    Diagnostic,
    EnsureAudienceUnderstandingPass,
    IRPass,
    NormalizeFilmBeatOrderPass,
    NormalizeShotTimelinePass,
    PassPipeline,
    PassResult,
    PromptLeakageDiagnosticsPass,
    ValidateFilmIRPass,
    ValidateMovieIRPass,
    film_ir_pass_pipeline,
    compiler_pass_pipeline,
    movie_ir_pass_pipeline,
)
from .creative_passes import (
    AudienceUnderstandingDiagnosticsPass,
    ConflictClarityDiagnosticsPass,
    CreativeDiagnostic,
    CreativePass,
    CreativePassPipeline,
    CreativePassResult,
    EmotionalContinuityPass,
    PacingDiagnosticsPass,
    VisualMotifDiagnosticsPass,
    creative_pass_pipeline,
)
from .optimizer import (
    DetectMissingAudienceUnderstandingOptimizer,
    DetectOverloadedBeatOptimizer,
    DetectRedundantShotOptimizer,
    DetectTimelineBudgetRiskOptimizer,
    DetectWeakClimaxOptimizer,
    FilmIROptimizer,
    MergeAdjacentCompatibleShotsOptimizer,
    MovieIROptimizer,
    OptimizationDiagnostic,
    OptimizationTransformation,
    OptimizerResult,
)
from .revision_loop import (
    DirectorRevisionLoop,
    DirectorRevisionRequest,
    DirectorRevisionResult,
    RuleBasedDirectorRevisionLoop,
)
from .creative_graph import (
    AudienceKnowledgeGraph,
    CharacterArcGraph,
    ConflictGraph,
    CreativeGraph,
    CreativeGraphEdge,
    CreativeGraphNode,
    EmotionGraph,
    PlanLayerConsistencyGraph,
)
from .creative_analysis import (
    AudienceKnowledgeAnalysis,
    CharacterArcAnalysis,
    ConflictProgressionAnalysis,
    CreativeAnalysis,
    CreativeAnalysisArtifact,
    CreativeAnalysisDiagnostic,
    CreativeAnalysisPipeline,
    CreativeAnalysisResult,
    EmotionFlowAnalysis,
    PlanLayerConsistencyAnalysis,
    creative_analysis_pipeline,
)
from .creative_optimizer import (
    AudienceOptimizer,
    CharacterArcOptimizer,
    ConflictOptimizer,
    CreativeOptimizer,
    CreativeOptimizerResult,
    EmotionOptimizer,
    OptimizationSuggestion,
    PlanLayerConsistencyOptimizer,
    TransformationCandidate,
    creative_optimizer,
)
from .revision_request import (
    CreativeRevisionRequest,
    RevisionPolicy,
    RevisionRequestBuilder,
    RevisionRequestBuilderResult,
)
from .revision_candidate import RevisionCandidate, RevisionCandidateFactory
from .revision_diff import RevisionChange, RevisionDiff, RevisionDiffBuilder
from .revision_guard import RevisionDecision, RevisionGuard, RevisionGuardPolicy
from .director_revision_adapter import (
    DirectorAgentRevisionAdapter,
    DirectorRevisionAdapter,
    DirectorRevisionAdapterResult,
    DirectorRevisionContext,
    GuardedRevisionResult,
    OpenAIDirectorRevisionAdapter,
    RuleBasedDirectorRevisionAdapter,
    build_director_revision_prompt,
    run_director_revision_guarded,
)
from .revision_history import (
    MoviePlanVersionRecord,
    RevisionApplyRecord,
    RevisionRollbackRecord,
)
from .revision_invalidation import (
    DownstreamInvalidationResult,
    invalidate_downstream_after_movie_plan_change,
)
from .revision_apply import (
    ApplyRevisionCommand,
    RevisionApplyResult,
    RevisionApplyService,
    RevisionRollbackResult,
    RevisionRollbackService,
    RollbackRevisionCommand,
    apply_revision_to_session,
    rollback_revision_to_session,
)
from .lineage import (
    LineageCheckResult,
    SourceLineage,
    SourceLineageGuard,
    StaleArtifactDiagnostic,
)
from .fingerprint import (
    CanonicalSerializer,
    ContentFingerprint,
    FingerprintBuilder,
    canonicalize_movie_plan,
    content_fingerprint,
    ensure_movie_plan_provenance,
    movie_plan_fingerprint,
    movie_plan_lineage_token,
)

# ``__all__`` is the supported V2 facade.  The module still imports a small
# set of compatibility-only implementation names for existing in-repository
# callers, but stores, fakes, HTTP test doubles, scheduler internals, and
# graph/history records are intentionally not part of the public surface.
__all__ = [
    "AcceptanceCriterion",
    "CompilationOptions",
    "CompileDiagnostic",
    "CompileError",
    "CompileResult",
    "CameraInstruction",
    "CameraPlan",
    "CharacterSheet",
    "CharacterSheetEntry",
    "CharacterAnchor",
    "ContinuityEntry",
    "ContinuityPlan",
    "ContinuityAnchor",
    "CreativeBrief",
    "DirectorPlan",
    "DirectorAgent",
    "DirectorOrchestrator",
    "DirectorOutputRejected",
    "DirectorGenerationError",
    "EmotionPoint",
    "FilmBeatPlan",
    "FilmIR",
    "CinematicIR",
    "FilmBeat",
    "CinematicBeat",
    "FilmShot",
    "FilmCharacterAnchor",
    "BeatTimelineEntry",
    "EmotionCurvePoint",
    "TensionCurvePoint",
    "CharacterEmotionAnchor",
    "FilmContinuityIntent",
    "FilmTransitionIntent",
    "FilmNarrationIntent",
    "FilmMusicIntent",
    "FilmAcceptanceCriterion",
    "DramaticPurpose",
    "ViewerState",
    "NarrativeFunction",
    "VisualFocus",
    "RequiredAudienceUnderstanding",
    "RequiredEvidence",
    "MoviePlan",
    "MovieIR",
    "MoviePlanCompiler",
    "VideoJobCompiler",
    "MovieIRBuilder",
    "FilmIRBuilder",
    "CinematicIRBuilder",
    "FilmIRBuildDiagnostic",
    "FilmIRBuildError",
    "FilmIRBuildResult",
    "IRBuildDiagnostic",
    "IRBuildError",
    "IRBuildResult",
    "MusicPlan",
    "MusicCue",
    "NarrationPlan",
    "NarrationSegment",
    "NarrationCue",
    "ProviderCapabilities",
    "ProviderJob",
    "RetakeRequest",
    "ScenePlan",
    "ScenePlanEntry",
    "ShotIR",
    "ShotPlan",
    "Script",
    "ScriptScene",
    "Story",
    "StoryCharacterGoal",
    "StoryPlan",
    "TimingEntry",
    "TimingPlan",
    "TimelineEntry",
    "TransitionInstruction",
    "TransitionPlan",
    "TransitionCue",
    "SubtitleCue",
    "ValidationReport",
    "ValidationIssue",
    "ValidationResult",
    "FilmIRValidator",
    "MovieIRValidator",
    "Diagnostic",
    "PassResult",
    "IRPass",
    "PassPipeline",
    "CompilerPassPipeline",
    "ValidateFilmIRPass",
    "NormalizeFilmBeatOrderPass",
    "EnsureAudienceUnderstandingPass",
    "ValidateMovieIRPass",
    "NormalizeShotTimelinePass",
    "ContinuityDiagnosticsPass",
    "PromptLeakageDiagnosticsPass",
    "VideoJob",
    "CapabilitySnapshot",
    "ProviderAssignment",
    "ExpectedArtifact",
    "ReferenceInput",
    "RetryPolicy",
    "TimeoutPolicy",
    "ArtifactPolicy",
    "DependencyEdge",
    "ExecutionPlan",
    "ExecutionUnit",
    "ReferenceFrameStrategy",
    "RuntimePolicy",
    "ExecutionBundle",
    "execution_bundle_fingerprint",
    "execution_plan_fingerprint",
    "execution_unit_fingerprint",
    "video_job_fingerprint",
    "ExecutionPlanCompileDiagnostic",
    "ExecutionPlanCompileError",
    "ExecutionPlanCompileResult",
    "ExecutionPlanCompiler",
    "ExecutionValidationDiagnostic",
    "ExecutionValidationResult",
    "validate_execution_bundle",
    "validate_execution_plan",
    "ExecutionRun",
    "ExecutionRunStatus",
    "ExecutionState",
    "ExecutionUnitState",
    "RuntimeProviderJob",
    "FakeClock",
    "ProviderRuntimeError",
    "ProviderRuntime",
    "ProviderRequestContext",
    "RuntimeProviderCapabilities",
    "DurationRange",
    "ProviderErrorCategory",
    "ProviderJobStatus",
    "SystemClock",
    "ProviderNotRegisteredError",
    "ProviderRegistrationError",
    "ProviderRuntimeRegistry",
    "ExecutionRuntime",
    "ExecutionRuntimeError",
    "RuntimeNotFoundError",
    "StaleExecutionRuntimeError",
    "OpenAIDirectorAgent",
    "RuleBasedDirectorAgent",
    "as_plain_data",
    "build_film_ir",
    "build_cinematic_ir",
    "film_ir_pass_pipeline",
    "movie_ir_pass_pipeline",
    "compiler_pass_pipeline",
    "CreativeDiagnostic",
    "CreativePass",
    "CreativePassResult",
    "CreativePassPipeline",
    "PacingDiagnosticsPass",
    "EmotionalContinuityPass",
    "VisualMotifDiagnosticsPass",
    "AudienceUnderstandingDiagnosticsPass",
    "ConflictClarityDiagnosticsPass",
    "creative_pass_pipeline",
    "OptimizationDiagnostic",
    "OptimizationTransformation",
    "OptimizerResult",
    "FilmIROptimizer",
    "MovieIROptimizer",
    "DetectOverloadedBeatOptimizer",
    "DetectWeakClimaxOptimizer",
    "DetectMissingAudienceUnderstandingOptimizer",
    "MergeAdjacentCompatibleShotsOptimizer",
    "DetectRedundantShotOptimizer",
    "DetectTimelineBudgetRiskOptimizer",
    "DirectorRevisionLoop",
    "DirectorRevisionRequest",
    "DirectorRevisionResult",
    "RuleBasedDirectorRevisionLoop",
    "validate_movie_plan",
    "validate_video_job",
    "movie_plan_from_data",
    "CreativeAnalysis",
    "CreativeAnalysisDiagnostic",
    "CreativeAnalysisArtifact",
    "CreativeAnalysisResult",
    "CreativeAnalysisPipeline",
    "EmotionFlowAnalysis",
    "AudienceKnowledgeAnalysis",
    "ConflictProgressionAnalysis",
    "CharacterArcAnalysis",
    "PlanLayerConsistencyAnalysis",
    "creative_analysis_pipeline",
    "OptimizationSuggestion",
    "TransformationCandidate",
    "CreativeOptimizerResult",
    "CreativeOptimizer",
    "EmotionOptimizer",
    "AudienceOptimizer",
    "ConflictOptimizer",
    "CharacterArcOptimizer",
    "PlanLayerConsistencyOptimizer",
    "creative_optimizer",
    "CreativeRevisionRequest",
    "RevisionRequestBuilderResult",
    "RevisionPolicy",
    "RevisionRequestBuilder",
    "RevisionCandidate",
    "RevisionCandidateFactory",
    "RevisionChange",
    "RevisionDiff",
    "RevisionDiffBuilder",
    "RevisionDecision",
    "RevisionGuard",
    "RevisionGuardPolicy",
    "DirectorRevisionContext",
    "DirectorRevisionAdapterResult",
    "GuardedRevisionResult",
    "DirectorRevisionAdapter",
    "RuleBasedDirectorRevisionAdapter",
    "DirectorAgentRevisionAdapter",
    "OpenAIDirectorRevisionAdapter",
    "build_director_revision_prompt",
    "run_director_revision_guarded",
    "ApplyRevisionCommand",
    "RevisionApplyResult",
    "RevisionApplyService",
    "RollbackRevisionCommand",
    "RevisionRollbackResult",
    "RevisionRollbackService",
    "apply_revision_to_session",
    "rollback_revision_to_session",
    "LineageCheckResult",
    "SourceLineage",
    "SourceLineageGuard",
    "StaleArtifactDiagnostic",
    "canonicalize_movie_plan",
    "content_fingerprint",
    "ensure_movie_plan_provenance",
    "movie_plan_fingerprint",
    "movie_plan_lineage_token",
]
